FROM anapsix/alpine-java
MAINTAINER myNAME
COPY target/appstatus-spring-boot-demo-demo-0.0.1-SNAPSHOT.war /home/appstatus-spring-boot-demo.war
CMD ["java","-jar","/home/appstatus-spring-boot-demo.war"]

EXPOSE 8080