FROM anapsix/alpine-java
MAINTAINER myNAME
COPY target/appstatus-spring-boot-demo-demo-1.0.0.war /home/appstatus-spring-boot-demo.war
CMD ["java","-jar","/home/appstatus-spring-boot-demo.war"]

EXPOSE 8080